name: DevDoctor

on:
  push:
  pull_request:

jobs:
  devdoctor:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - uses: rtcoder/devdoctor@v1.46.0
        with:
          version: v1.46.0
          args: ci --format=sarif
