name: DevDoctor

on:
  push:
  pull_request:

jobs:
  devdoctor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: rtcoder/devdoctor@v0.14.0
        with:
          version: v0.14.0
          args: ci --format=sarif
