<?php

declare(strict_types=1);

namespace DevDoctor\Core;

enum IssueCode: string
{
    case DD_CI_BASELINE_EXISTS = 'DD_CI_BASELINE_EXISTS';
    case DD_CI_BASELINE_INVALID = 'DD_CI_BASELINE_INVALID';
    case DD_CI_BASELINE_MISSING = 'DD_CI_BASELINE_MISSING';
    case DD_CI_UNKNOWN_MODULE = 'DD_CI_UNKNOWN_MODULE';
    case DD_HEALTH_UNKNOWN_MODULE = 'DD_HEALTH_UNKNOWN_MODULE';
    case DD_COMPOSER_BINARY_MISSING = 'DD_COMPOSER_BINARY_MISSING';
    case DD_COMPOSER_EXTENSION_MISSING = 'DD_COMPOSER_EXTENSION_MISSING';
    case DD_COMPOSER_JSON_INVALID = 'DD_COMPOSER_JSON_INVALID';
    case DD_COMPOSER_LOCK_MISSING = 'DD_COMPOSER_LOCK_MISSING';
    case DD_COMPOSER_LOCK_OUTDATED = 'DD_COMPOSER_LOCK_OUTDATED';
    case DD_COMPOSER_NOT_PROJECT = 'DD_COMPOSER_NOT_PROJECT';
    case DD_COMPOSER_PACKAGE_ABANDONED = 'DD_COMPOSER_PACKAGE_ABANDONED';
    case DD_COMPOSER_PHP_VERSION_MISMATCH = 'DD_COMPOSER_PHP_VERSION_MISMATCH';
    case DD_COMPOSER_READY = 'DD_COMPOSER_READY';
    case DD_COMPOSER_SCRIPT_RISKY = 'DD_COMPOSER_SCRIPT_RISKY';
    case DD_COMPOSER_VALIDATE_FAILED = 'DD_COMPOSER_VALIDATE_FAILED';
    case DD_COMPOSER_VENDOR_MISSING = 'DD_COMPOSER_VENDOR_MISSING';
    case DD_DB_CONNECT_FAILED = 'DD_DB_CONNECT_FAILED';
    case DD_DB_CONNECT_OK = 'DD_DB_CONNECT_OK';
    case DD_DB_CONNECTION_MISSING = 'DD_DB_CONNECTION_MISSING';
    case DD_DB_CONNECTION_UNKNOWN = 'DD_DB_CONNECTION_UNKNOWN';
    case DD_DB_DRIVER_MISSING = 'DD_DB_DRIVER_MISSING';
    case DD_DB_PORT_INVALID = 'DD_DB_PORT_INVALID';
    case DD_DB_READY = 'DD_DB_READY';
    case DD_DB_REQUIRED_KEY_MISSING = 'DD_DB_REQUIRED_KEY_MISSING';
    case DD_DB_SQLITE_FILE_MISSING = 'DD_DB_SQLITE_FILE_MISSING';
    case DD_PHP_BINARY_MISSING = 'DD_PHP_BINARY_MISSING';
    case DD_PHP_COMPOSER_JSON_INVALID = 'DD_PHP_COMPOSER_JSON_INVALID';
    case DD_PHP_EXTENSION_MISSING = 'DD_PHP_EXTENSION_MISSING';
    case DD_PHP_INI_MISSING = 'DD_PHP_INI_MISSING';
    case DD_PHP_MEMORY_LIMIT_LOW = 'DD_PHP_MEMORY_LIMIT_LOW';
    case DD_PHP_READY = 'DD_PHP_READY';
    case DD_PHP_VERSION_MISMATCH = 'DD_PHP_VERSION_MISMATCH';
    case DD_PHP_XDEBUG_ENABLED_IN_CI = 'DD_PHP_XDEBUG_ENABLED_IN_CI';
    case DD_NODE_BINARY_MISSING = 'DD_NODE_BINARY_MISSING';
    case DD_NODE_LOCK_MISSING = 'DD_NODE_LOCK_MISSING';
    case DD_NODE_MODULES_MISSING = 'DD_NODE_MODULES_MISSING';
    case DD_NODE_MULTIPLE_LOCKFILES = 'DD_NODE_MULTIPLE_LOCKFILES';
    case DD_NODE_NOT_PROJECT = 'DD_NODE_NOT_PROJECT';
    case DD_NODE_PACKAGE_JSON_INVALID = 'DD_NODE_PACKAGE_JSON_INVALID';
    case DD_NODE_PACKAGE_MANAGER_MISMATCH = 'DD_NODE_PACKAGE_MANAGER_MISMATCH';
    case DD_NODE_READY = 'DD_NODE_READY';
    case DD_NODE_SCRIPT_RISKY = 'DD_NODE_SCRIPT_RISKY';
    case DD_NODE_VERSION_FILE_CONFLICT = 'DD_NODE_VERSION_FILE_CONFLICT';
    case DD_NODE_VERSION_MISMATCH = 'DD_NODE_VERSION_MISMATCH';
    case DD_LARAVEL_APP_KEY_MISSING = 'DD_LARAVEL_APP_KEY_MISSING';
    case DD_LARAVEL_APP_URL_DEFAULT = 'DD_LARAVEL_APP_URL_DEFAULT';
    case DD_LARAVEL_CONFIG_CACHED = 'DD_LARAVEL_CONFIG_CACHED';
    case DD_LARAVEL_DIRECTORY_MISSING = 'DD_LARAVEL_DIRECTORY_MISSING';
    case DD_LARAVEL_DIRECTORY_NOT_WRITABLE = 'DD_LARAVEL_DIRECTORY_NOT_WRITABLE';
    case DD_LARAVEL_ENV_MISSING = 'DD_LARAVEL_ENV_MISSING';
    case DD_LARAVEL_NOT_PROJECT = 'DD_LARAVEL_NOT_PROJECT';
    case DD_LARAVEL_PROD_DEBUG = 'DD_LARAVEL_PROD_DEBUG';
    case DD_LARAVEL_READY = 'DD_LARAVEL_READY';
    case DD_SECURITY_DOCKER_PRIVILEGED = 'DD_SECURITY_DOCKER_PRIVILEGED';
    case DD_SECURITY_DOCKER_SOCKET_MOUNT = 'DD_SECURITY_DOCKER_SOCKET_MOUNT';
    case DD_SECURITY_ENV_NOT_IGNORED = 'DD_SECURITY_ENV_NOT_IGNORED';
    case DD_SECURITY_READY = 'DD_SECURITY_READY';
    case DD_SECURITY_RISKY_COMPOSER_SCRIPT = 'DD_SECURITY_RISKY_COMPOSER_SCRIPT';
    case DD_SECURITY_RISKY_PACKAGE_SCRIPT = 'DD_SECURITY_RISKY_PACKAGE_SCRIPT';
    case DD_SECURITY_SECRET_IN_EXAMPLE = 'DD_SECURITY_SECRET_IN_EXAMPLE';
    case DD_SECURITY_SECRET_PATTERN = 'DD_SECURITY_SECRET_PATTERN';
    case DD_DOCKER_BINARY_MISSING = 'DD_DOCKER_BINARY_MISSING';
    case DD_DOCKER_COMPOSE_CONFIG_INVALID = 'DD_DOCKER_COMPOSE_CONFIG_INVALID';
    case DD_DOCKER_COMPOSE_FILE_MISSING = 'DD_DOCKER_COMPOSE_FILE_MISSING';
    case DD_DOCKER_COMPOSE_INVALID = 'DD_DOCKER_COMPOSE_INVALID';
    case DD_DOCKER_CONTAINER_UNHEALTHY = 'DD_DOCKER_CONTAINER_UNHEALTHY';
    case DD_DOCKER_DAEMON_UNAVAILABLE = 'DD_DOCKER_DAEMON_UNAVAILABLE';
    case DD_DOCKER_ENV_REFERENCE_MISSING = 'DD_DOCKER_ENV_REFERENCE_MISSING';
    case DD_DOCKER_HOST_PORT_CONFLICT = 'DD_DOCKER_HOST_PORT_CONFLICT';
    case DD_DOCKER_NO_COMPOSE_PROJECT = 'DD_DOCKER_NO_COMPOSE_PROJECT';
    case DD_DOCKER_READY = 'DD_DOCKER_READY';
    case DD_ENV_DUPLICATE_KEY = 'DD_ENV_DUPLICATE_KEY';
    case DD_ENV_EMPTY_VALUE = 'DD_ENV_EMPTY_VALUE';
    case DD_ENV_EXAMPLE_MISSING = 'DD_ENV_EXAMPLE_MISSING';
    case DD_ENV_FILE_MISSING = 'DD_ENV_FILE_MISSING';
    case DD_ENV_FORBIDDEN_WHEN_PRESENT = 'DD_ENV_FORBIDDEN_WHEN_PRESENT';
    case DD_ENV_INVALID_ALLOWED_VALUE = 'DD_ENV_INVALID_ALLOWED_VALUE';
    case DD_ENV_INVALID_CONFIG = 'DD_ENV_INVALID_CONFIG';
    case DD_ENV_INVALID_KEY_NAME = 'DD_ENV_INVALID_KEY_NAME';
    case DD_ENV_INVALID_TYPE = 'DD_ENV_INVALID_TYPE';
    case DD_ENV_MISSING_IN_ENV = 'DD_ENV_MISSING_IN_ENV';
    case DD_ENV_MISSING_IN_EXAMPLE = 'DD_ENV_MISSING_IN_EXAMPLE';
    case DD_ENV_PROD_DEBUG = 'DD_ENV_PROD_DEBUG';
    case DD_ENV_READY = 'DD_ENV_READY';
    case DD_ENV_REQUIRED_MISSING = 'DD_ENV_REQUIRED_MISSING';
    case DD_ENV_REQUIRED_WHEN_MISSING = 'DD_ENV_REQUIRED_WHEN_MISSING';
    case DD_ENV_SECRET_IN_EXAMPLE = 'DD_ENV_SECRET_IN_EXAMPLE';
    case DD_GIT_AHEAD_BEHIND = 'DD_GIT_AHEAD_BEHIND';
    case DD_GIT_BINARY_MISSING = 'DD_GIT_BINARY_MISSING';
    case DD_GIT_CONFLICTS = 'DD_GIT_CONFLICTS';
    case DD_GIT_DETACHED_HEAD = 'DD_GIT_DETACHED_HEAD';
    case DD_GIT_DIRTY_WORKTREE = 'DD_GIT_DIRTY_WORKTREE';
    case DD_GIT_ENV_NOT_IGNORED = 'DD_GIT_ENV_NOT_IGNORED';
    case DD_GIT_LARGE_UNTRACKED_FILE = 'DD_GIT_LARGE_UNTRACKED_FILE';
    case DD_GIT_NOT_REPOSITORY = 'DD_GIT_NOT_REPOSITORY';
    case DD_GIT_NO_UPSTREAM = 'DD_GIT_NO_UPSTREAM';
    case DD_GIT_READY = 'DD_GIT_READY';
    case DD_GIT_TRACKED_SENSITIVE_FILE = 'DD_GIT_TRACKED_SENSITIVE_FILE';
    case DD_GIT_UNTRACKED_SENSITIVE_FILE = 'DD_GIT_UNTRACKED_SENSITIVE_FILE';
    case DD_PORTS_READY = 'DD_PORTS_READY';
    case DD_PORT_INVALID_PORT = 'DD_PORT_INVALID_PORT';
    case DD_PORT_IN_USE = 'DD_PORT_IN_USE';
    case DD_PORT_MULTIPLE_LISTENERS = 'DD_PORT_MULTIPLE_LISTENERS';
    case DD_PORT_PRIVILEGED = 'DD_PORT_PRIVILEGED';
    case DD_PORT_PROVIDER_UNAVAILABLE = 'DD_PORT_PROVIDER_UNAVAILABLE';
    case DD_PRESET_DETECTED = 'DD_PRESET_DETECTED';
    case DD_PRESET_NONE_DETECTED = 'DD_PRESET_NONE_DETECTED';

    public function hint(): ?string
    {
        return match ($this) {
            self::DD_CI_UNKNOWN_MODULE => 'Use one of the documented CI module names.',
            self::DD_HEALTH_UNKNOWN_MODULE => 'Use one of the documented health module names or remove it from --modules.',
            self::DD_CI_BASELINE_MISSING => 'Create the baseline file with --write-baseline or correct the provided path.',
            self::DD_CI_BASELINE_INVALID => 'Regenerate the baseline file with --write-baseline.',
            self::DD_CI_BASELINE_EXISTS => 'Review the existing baseline before replacing it with --force.',
            self::DD_ENV_DUPLICATE_KEY => 'Keep a single declaration for this key so its effective value is unambiguous.',
            self::DD_ENV_EMPTY_VALUE => 'Set a meaningful value or explicitly ignore the key in devdoctor.yml.',
            self::DD_ENV_EXAMPLE_MISSING => 'Create the example file and document every required environment key.',
            self::DD_ENV_FILE_MISSING => 'Create the environment file from the project template before running the application.',
            self::DD_ENV_FORBIDDEN_WHEN_PRESENT => 'Remove or change this value when the configured condition is active.',
            self::DD_ENV_INVALID_ALLOWED_VALUE => 'Choose one of the values allowed by devdoctor.yml.',
            self::DD_ENV_INVALID_CONFIG => 'Fix the YAML structure and rerun DevDoctor.',
            self::DD_ENV_INVALID_KEY_NAME => 'Rename the key to use letters, numbers, and underscores only.',
            self::DD_ENV_INVALID_TYPE => 'Change the value to match the type declared in devdoctor.yml.',
            self::DD_ENV_MISSING_IN_ENV => 'Add the key to the environment file or ignore it explicitly when it is optional.',
            self::DD_ENV_MISSING_IN_EXAMPLE => 'Add the key to the example file without copying a real secret value.',
            self::DD_ENV_PROD_DEBUG => 'Disable debug mode before using production environment settings.',
            self::DD_ENV_REQUIRED_MISSING, self::DD_ENV_REQUIRED_WHEN_MISSING => 'Add the required key to the environment file.',
            self::DD_ENV_SECRET_IN_EXAMPLE => 'Replace the value with a safe placeholder and rotate the exposed credential if it was real.',
            self::DD_PORT_INVALID_PORT => 'Use a numeric TCP port between 1 and 65535.',
            self::DD_PORT_MULTIPLE_LISTENERS => 'Inspect all listeners and stop only the process that should not own the port.',
            self::DD_PORT_PROVIDER_UNAVAILABLE => 'Install a supported port inspection tool for this operating system.',
            self::DD_PORT_IN_USE => 'Confirm the process can be stopped before freeing the port.',
            self::DD_COMPOSER_BINARY_MISSING => 'Install Composer or add it to PATH before running Composer diagnostics.',
            self::DD_COMPOSER_EXTENSION_MISSING => 'Install and enable the required PHP extension.',
            self::DD_COMPOSER_JSON_INVALID => 'Fix composer.json syntax before running Composer commands.',
            self::DD_COMPOSER_LOCK_MISSING, self::DD_COMPOSER_LOCK_OUTDATED => 'Review dependency changes and regenerate composer.lock intentionally.',
            self::DD_COMPOSER_PACKAGE_ABANDONED => 'Plan migration to a maintained replacement package.',
            self::DD_COMPOSER_PHP_VERSION_MISMATCH => 'Use a PHP version that satisfies composer.json or update the declared constraint intentionally.',
            self::DD_COMPOSER_SCRIPT_RISKY => 'Review the script and replace shell execution with a safer, auditable command where possible.',
            self::DD_COMPOSER_VALIDATE_FAILED => 'Run Composer validation for the full error details.',
            self::DD_COMPOSER_VENDOR_MISSING => 'Install dependencies after reviewing composer.lock.',
            self::DD_DB_CONNECT_FAILED => 'Verify credentials, host, port, and local network reachability before starting the application.',
            self::DD_DB_CONNECTION_MISSING => 'Set DB_CONNECTION to the database driver your project expects.',
            self::DD_DB_CONNECTION_UNKNOWN => 'Use a supported database connection name or document the custom driver intentionally.',
            self::DD_DB_DRIVER_MISSING => 'Install and enable the matching PDO driver for the active PHP runtime.',
            self::DD_DB_PORT_INVALID => 'Use a numeric TCP port between 1 and 65535.',
            self::DD_DB_REQUIRED_KEY_MISSING => 'Add the required database environment key or configure an intentional default.',
            self::DD_DB_SQLITE_FILE_MISSING => 'Create the SQLite database file intentionally before relying on it.',
            self::DD_PHP_BINARY_MISSING => 'Install PHP or add it to PATH before running PHP diagnostics.',
            self::DD_PHP_COMPOSER_JSON_INVALID => 'Fix composer.json syntax before relying on PHP platform diagnostics.',
            self::DD_PHP_EXTENSION_MISSING => 'Install and enable the required PHP extension for the active CLI runtime.',
            self::DD_PHP_INI_MISSING => 'Confirm the CLI runtime is intentionally running without a php.ini file.',
            self::DD_PHP_MEMORY_LIMIT_LOW => 'Increase CLI memory_limit or run DevDoctor with a lower intentional threshold.',
            self::DD_PHP_VERSION_MISMATCH => 'Use a PHP runtime that satisfies composer.json or update the declared constraint intentionally.',
            self::DD_PHP_XDEBUG_ENABLED_IN_CI => 'Disable Xdebug in CI, for example by setting XDEBUG_MODE=off.',
            self::DD_NODE_BINARY_MISSING => 'Install Node.js or add it to PATH before running Node diagnostics.',
            self::DD_NODE_LOCK_MISSING => 'Generate and commit the intended package manager lockfile.',
            self::DD_NODE_MODULES_MISSING => 'Install dependencies with the package manager selected by the project lockfile.',
            self::DD_NODE_MULTIPLE_LOCKFILES => 'Keep only the lockfile for the package manager the project actually uses.',
            self::DD_NODE_PACKAGE_JSON_INVALID => 'Fix package.json syntax before running package manager commands.',
            self::DD_NODE_PACKAGE_MANAGER_MISMATCH => 'Align packageManager with the committed lockfile.',
            self::DD_NODE_SCRIPT_RISKY => 'Review the script and replace remote shell execution with a safer, auditable command.',
            self::DD_NODE_VERSION_FILE_CONFLICT => 'Choose one Node.js version policy and align package.json, .nvmrc, and .node-version.',
            self::DD_NODE_VERSION_MISMATCH => 'Use a Node.js runtime that satisfies the project requirement.',
            self::DD_LARAVEL_APP_KEY_MISSING => 'Generate and set APP_KEY before running the application.',
            self::DD_LARAVEL_APP_URL_DEFAULT => 'Set APP_URL to the canonical local, staging, or production URL for this project.',
            self::DD_LARAVEL_CONFIG_CACHED => 'Rebuild Laravel config cache after changing environment or config files.',
            self::DD_LARAVEL_DIRECTORY_MISSING => 'Create the expected Laravel runtime directory.',
            self::DD_LARAVEL_DIRECTORY_NOT_WRITABLE => 'Adjust ownership or permissions so the current user can write Laravel runtime files.',
            self::DD_LARAVEL_ENV_MISSING => 'Create .env from .env.example and fill required Laravel values.',
            self::DD_LARAVEL_PROD_DEBUG => 'Disable APP_DEBUG before using production environment settings.',
            self::DD_SECURITY_DOCKER_PRIVILEGED => 'Avoid privileged containers unless the service explicitly requires host-level access.',
            self::DD_SECURITY_DOCKER_SOCKET_MOUNT => 'Avoid mounting the Docker socket into containers unless this is an intentional trusted control plane.',
            self::DD_SECURITY_ENV_NOT_IGNORED => 'Add .env patterns to .gitignore to reduce accidental secret commits.',
            self::DD_SECURITY_RISKY_COMPOSER_SCRIPT => 'Review the Composer script and replace remote shell execution with a safer install step.',
            self::DD_SECURITY_RISKY_PACKAGE_SCRIPT => 'Review the package script and replace remote shell execution with a safer install step.',
            self::DD_SECURITY_SECRET_IN_EXAMPLE => 'Replace the value with a placeholder and rotate the credential if it was real.',
            self::DD_SECURITY_SECRET_PATTERN => 'Move hard-coded secrets into a secret manager or local environment file and rotate exposed values.',
            self::DD_GIT_BINARY_MISSING => 'Install Git or add it to PATH before running repository diagnostics.',
            self::DD_GIT_CONFLICTS => 'Resolve all merge conflicts before continuing.',
            self::DD_GIT_DETACHED_HEAD => 'Create or switch to a branch before making long-lived changes.',
            self::DD_GIT_DIRTY_WORKTREE => 'Review, commit, stash, or discard the intended changes before requiring a clean worktree.',
            self::DD_GIT_ENV_NOT_IGNORED => 'Add the environment file pattern to .gitignore.',
            self::DD_GIT_LARGE_UNTRACKED_FILE => 'Review whether the file belongs in Git or should be ignored or stored elsewhere.',
            self::DD_GIT_NO_UPSTREAM => 'Configure an upstream branch before relying on ahead/behind diagnostics.',
            self::DD_GIT_TRACKED_SENSITIVE_FILE => 'Remove the file from version control and rotate any exposed credentials.',
            self::DD_GIT_UNTRACKED_SENSITIVE_FILE => 'Ignore the file or confirm it cannot be committed accidentally.',
            self::DD_DOCKER_BINARY_MISSING => 'Install Docker or add it to PATH before running Compose diagnostics.',
            self::DD_DOCKER_COMPOSE_CONFIG_INVALID, self::DD_DOCKER_COMPOSE_INVALID => 'Fix the Compose configuration before starting containers.',
            self::DD_DOCKER_COMPOSE_FILE_MISSING => 'Check the --compose-file path or add a supported Compose file.',
            self::DD_DOCKER_CONTAINER_UNHEALTHY => 'Inspect container logs and health-check output before restarting services.',
            self::DD_DOCKER_DAEMON_UNAVAILABLE => 'Start the Docker daemon and verify the current user can access it.',
            self::DD_DOCKER_ENV_REFERENCE_MISSING => 'Define the referenced environment variable or provide an intentional Compose default.',
            self::DD_DOCKER_HOST_PORT_CONFLICT => 'Change the host port mapping or stop the process currently using that port.',
            default => null,
        };
    }
}
