<?php

declare(strict_types=1);

namespace DevDoctor\Core;

enum IssueCode: string
{
    case DD_CI_BASELINE_EXISTS = 'DD_CI_BASELINE_EXISTS';
    case DD_CI_BASELINE_INVALID = 'DD_CI_BASELINE_INVALID';
    case DD_CI_BASELINE_MISSING = 'DD_CI_BASELINE_MISSING';
    case DD_CI_BASELINE_REPORT = 'DD_CI_BASELINE_REPORT';
    case DD_CI_UNKNOWN_MODULE = 'DD_CI_UNKNOWN_MODULE';
    case DD_CI_UNKNOWN_PROFILE = 'DD_CI_UNKNOWN_PROFILE';
    case DD_CACHE_DIRECTORY_LARGE = 'DD_CACHE_DIRECTORY_LARGE';
    case DD_CACHE_DIRECTORY_NOT_WRITABLE = 'DD_CACHE_DIRECTORY_NOT_WRITABLE';
    case DD_CACHE_LARAVEL_ARTIFACT = 'DD_CACHE_LARAVEL_ARTIFACT';
    case DD_CACHE_NOT_DETECTED = 'DD_CACHE_NOT_DETECTED';
    case DD_CACHE_READY = 'DD_CACHE_READY';
    case DD_HEALTH_UNKNOWN_MODULE = 'DD_HEALTH_UNKNOWN_MODULE';
    case DD_COMPOSER_BINARY_MISSING = 'DD_COMPOSER_BINARY_MISSING';
    case DD_COMPOSER_EXTENSION_MISSING = 'DD_COMPOSER_EXTENSION_MISSING';
    case DD_COMPOSER_JSON_INVALID = 'DD_COMPOSER_JSON_INVALID';
    case DD_COMPOSER_LOCK_MISSING = 'DD_COMPOSER_LOCK_MISSING';
    case DD_COMPOSER_LOCK_OUTDATED = 'DD_COMPOSER_LOCK_OUTDATED';
    case DD_COMPOSER_NOT_PROJECT = 'DD_COMPOSER_NOT_PROJECT';
    case DD_COMPOSER_PACKAGE_ABANDONED = 'DD_COMPOSER_PACKAGE_ABANDONED';
    case DD_COMPOSER_PHP_VERSION_MISMATCH = 'DD_COMPOSER_PHP_VERSION_MISMATCH';
    case DD_COMPOSER_READY = 'DD_COMPOSER_READY';
    case DD_COMPOSER_SCRIPT_RISKY = 'DD_COMPOSER_SCRIPT_RISKY';
    case DD_COMPOSER_VALIDATE_FAILED = 'DD_COMPOSER_VALIDATE_FAILED';
    case DD_COMPOSER_VENDOR_MISSING = 'DD_COMPOSER_VENDOR_MISSING';
    case DD_DB_CONNECT_FAILED = 'DD_DB_CONNECT_FAILED';
    case DD_DB_CONNECT_OK = 'DD_DB_CONNECT_OK';
    case DD_DB_CONNECTION_MISSING = 'DD_DB_CONNECTION_MISSING';
    case DD_DB_CONNECTION_UNKNOWN = 'DD_DB_CONNECTION_UNKNOWN';
    case DD_DB_DRIVER_MISSING = 'DD_DB_DRIVER_MISSING';
    case DD_DB_PORT_INVALID = 'DD_DB_PORT_INVALID';
    case DD_DB_READY = 'DD_DB_READY';
    case DD_DB_REQUIRED_KEY_MISSING = 'DD_DB_REQUIRED_KEY_MISSING';
    case DD_DB_SQLITE_FILE_MISSING = 'DD_DB_SQLITE_FILE_MISSING';
    case DD_HTTP_INSECURE_PRODUCTION_URL = 'DD_HTTP_INSECURE_PRODUCTION_URL';
    case DD_HTTP_LOCALHOST_PRODUCTION_URL = 'DD_HTTP_LOCALHOST_PRODUCTION_URL';
    case DD_HTTP_READY = 'DD_HTTP_READY';
    case DD_HTTP_URL_INVALID = 'DD_HTTP_URL_INVALID';
    case DD_HTTP_URL_MISSING = 'DD_HTTP_URL_MISSING';
    case DD_PHP_BINARY_MISSING = 'DD_PHP_BINARY_MISSING';
    case DD_PHP_COMPOSER_JSON_INVALID = 'DD_PHP_COMPOSER_JSON_INVALID';
    case DD_PHP_EXTENSION_MISSING = 'DD_PHP_EXTENSION_MISSING';
    case DD_PHP_INI_MISSING = 'DD_PHP_INI_MISSING';
    case DD_PHP_MEMORY_LIMIT_LOW = 'DD_PHP_MEMORY_LIMIT_LOW';
    case DD_PHP_READY = 'DD_PHP_READY';
    case DD_PHP_VERSION_MISMATCH = 'DD_PHP_VERSION_MISMATCH';
    case DD_PHP_XDEBUG_ENABLED_IN_CI = 'DD_PHP_XDEBUG_ENABLED_IN_CI';
    case DD_NODE_BINARY_MISSING = 'DD_NODE_BINARY_MISSING';
    case DD_NODE_LOCK_MISSING = 'DD_NODE_LOCK_MISSING';
    case DD_NODE_LOCK_OUTDATED = 'DD_NODE_LOCK_OUTDATED';
    case DD_NODE_MODULES_MISSING = 'DD_NODE_MODULES_MISSING';
    case DD_NODE_MULTIPLE_LOCKFILES = 'DD_NODE_MULTIPLE_LOCKFILES';
    case DD_NODE_NOT_PROJECT = 'DD_NODE_NOT_PROJECT';
    case DD_NODE_PACKAGE_JSON_INVALID = 'DD_NODE_PACKAGE_JSON_INVALID';
    case DD_NODE_PACKAGE_MANAGER_MISMATCH = 'DD_NODE_PACKAGE_MANAGER_MISMATCH';
    case DD_NODE_READY = 'DD_NODE_READY';
    case DD_NODE_SCRIPT_RISKY = 'DD_NODE_SCRIPT_RISKY';
    case DD_NODE_VERSION_FILE_CONFLICT = 'DD_NODE_VERSION_FILE_CONFLICT';
    case DD_NODE_VERSION_MISMATCH = 'DD_NODE_VERSION_MISMATCH';
    case DD_LARAVEL_APP_KEY_MISSING = 'DD_LARAVEL_APP_KEY_MISSING';
    case DD_LARAVEL_APP_URL_DEFAULT = 'DD_LARAVEL_APP_URL_DEFAULT';
    case DD_LARAVEL_CONFIG_CACHED = 'DD_LARAVEL_CONFIG_CACHED';
    case DD_LARAVEL_DIRECTORY_MISSING = 'DD_LARAVEL_DIRECTORY_MISSING';
    case DD_LARAVEL_DIRECTORY_NOT_WRITABLE = 'DD_LARAVEL_DIRECTORY_NOT_WRITABLE';
    case DD_LARAVEL_ENV_MISSING = 'DD_LARAVEL_ENV_MISSING';
    case DD_LARAVEL_NOT_PROJECT = 'DD_LARAVEL_NOT_PROJECT';
    case DD_LARAVEL_PROD_DEBUG = 'DD_LARAVEL_PROD_DEBUG';
    case DD_LARAVEL_READY = 'DD_LARAVEL_READY';
    case DD_MCP_CONFIG_INVALID = 'DD_MCP_CONFIG_INVALID';
    case DD_MCP_COMMAND_RISKY = 'DD_MCP_COMMAND_RISKY';
    case DD_MCP_ENV_REFERENCE_MISSING = 'DD_MCP_ENV_REFERENCE_MISSING';
    case DD_MCP_ENV_SECRET_INLINE = 'DD_MCP_ENV_SECRET_INLINE';
    case DD_MCP_NOT_CONFIGURED = 'DD_MCP_NOT_CONFIGURED';
    case DD_MCP_READY = 'DD_MCP_READY';
    case DD_MCP_REMOTE_URL_INSECURE = 'DD_MCP_REMOTE_URL_INSECURE';
    case DD_MCP_REMOTE_URL_MISSING = 'DD_MCP_REMOTE_URL_MISSING';
    case DD_MCP_SERVER_INVALID = 'DD_MCP_SERVER_INVALID';
    case DD_MCP_SERVERS_MISSING = 'DD_MCP_SERVERS_MISSING';
    case DD_MCP_STDIO_COMMAND_MISSING = 'DD_MCP_STDIO_COMMAND_MISSING';
    case DD_MCP_TRANSPORT_UNKNOWN = 'DD_MCP_TRANSPORT_UNKNOWN';
    case DD_SYMFONY_ENV_MISSING = 'DD_SYMFONY_ENV_MISSING';
    case DD_SYMFONY_NOT_PROJECT = 'DD_SYMFONY_NOT_PROJECT';
    case DD_SYMFONY_PROD_DEBUG = 'DD_SYMFONY_PROD_DEBUG';
    case DD_SYMFONY_READY = 'DD_SYMFONY_READY';
    case DD_SYMFONY_RECIPE_DRIFT = 'DD_SYMFONY_RECIPE_DRIFT';
    case DD_SYMFONY_RISKY_COMPOSER_SCRIPT = 'DD_SYMFONY_RISKY_COMPOSER_SCRIPT';
    case DD_SYMFONY_RUNTIME_DIR_MISSING = 'DD_SYMFONY_RUNTIME_DIR_MISSING';
    case DD_SYMFONY_SECRET_MISSING = 'DD_SYMFONY_SECRET_MISSING';
    case DD_FRONTEND_BUILD_SCRIPT_MISSING = 'DD_FRONTEND_BUILD_SCRIPT_MISSING';
    case DD_FRONTEND_NOT_PROJECT = 'DD_FRONTEND_NOT_PROJECT';
    case DD_FRONTEND_PRESET_DETECTED = 'DD_FRONTEND_PRESET_DETECTED';
    case DD_FRONTEND_READY = 'DD_FRONTEND_READY';
    case DD_FLUTTER_DEPENDENCY_SOURCE = 'DD_FLUTTER_DEPENDENCY_SOURCE';
    case DD_FLUTTER_LOCK_MISSING = 'DD_FLUTTER_LOCK_MISSING';
    case DD_FLUTTER_NOT_PROJECT = 'DD_FLUTTER_NOT_PROJECT';
    case DD_FLUTTER_PLATFORM_MARKERS_MISSING = 'DD_FLUTTER_PLATFORM_MARKERS_MISSING';
    case DD_FLUTTER_READY = 'DD_FLUTTER_READY';
    case DD_FLUTTER_SDK_CONSTRAINT_MISSING = 'DD_FLUTTER_SDK_CONSTRAINT_MISSING';
    case DD_MOBILE_ANDROID_DEBUGGABLE = 'DD_MOBILE_ANDROID_DEBUGGABLE';
    case DD_MOBILE_ANDROID_WRAPPER_MISSING = 'DD_MOBILE_ANDROID_WRAPPER_MISSING';
    case DD_MOBILE_IOS_DEBUG_ENTITLEMENT = 'DD_MOBILE_IOS_DEBUG_ENTITLEMENT';
    case DD_MOBILE_IOS_POD_LOCK_MISSING = 'DD_MOBILE_IOS_POD_LOCK_MISSING';
    case DD_MOBILE_NOT_PROJECT = 'DD_MOBILE_NOT_PROJECT';
    case DD_MOBILE_READY = 'DD_MOBILE_READY';
    case DD_MONOREPO_LOCK_MISSING = 'DD_MONOREPO_LOCK_MISSING';
    case DD_MONOREPO_MIXED_TOOLS = 'DD_MONOREPO_MIXED_TOOLS';
    case DD_MONOREPO_NOT_PROJECT = 'DD_MONOREPO_NOT_PROJECT';
    case DD_MONOREPO_READY = 'DD_MONOREPO_READY';
    case DD_MONOREPO_RISKY_ROOT_SCRIPT = 'DD_MONOREPO_RISKY_ROOT_SCRIPT';
    case DD_PYTHON_LOCK_MISSING = 'DD_PYTHON_LOCK_MISSING';
    case DD_PYTHON_MIXED_MANAGERS = 'DD_PYTHON_MIXED_MANAGERS';
    case DD_PYTHON_NOT_PROJECT = 'DD_PYTHON_NOT_PROJECT';
    case DD_PYTHON_READY = 'DD_PYTHON_READY';
    case DD_PYTHON_SUSPICIOUS_SOURCE = 'DD_PYTHON_SUSPICIOUS_SOURCE';
    case DD_PYTHON_VERSION_CONFLICT = 'DD_PYTHON_VERSION_CONFLICT';
    case DD_PYTHON_VENV_MISSING = 'DD_PYTHON_VENV_MISSING';
    case DD_RUBY_DATABASE_SECRET = 'DD_RUBY_DATABASE_SECRET';
    case DD_RUBY_LOCK_MISSING = 'DD_RUBY_LOCK_MISSING';
    case DD_RUBY_NOT_PROJECT = 'DD_RUBY_NOT_PROJECT';
    case DD_RUBY_RAILS_MASTER_KEY_MISSING = 'DD_RUBY_RAILS_MASTER_KEY_MISSING';
    case DD_RUBY_READY = 'DD_RUBY_READY';
    case DD_RUBY_RISKY_GEM_SOURCE = 'DD_RUBY_RISKY_GEM_SOURCE';
    case DD_RUBY_VERSION_CONFLICT = 'DD_RUBY_VERSION_CONFLICT';
    case DD_GO_MODULE_PATH_INVALID = 'DD_GO_MODULE_PATH_INVALID';
    case DD_GO_NOT_PROJECT = 'DD_GO_NOT_PROJECT';
    case DD_GO_READY = 'DD_GO_READY';
    case DD_GO_REPLACE_DIRECTIVE = 'DD_GO_REPLACE_DIRECTIVE';
    case DD_GO_SUM_MISSING = 'DD_GO_SUM_MISSING';
    case DD_GO_TOOLCHAIN_DECLARED = 'DD_GO_TOOLCHAIN_DECLARED';
    case DD_GO_VENDOR_PRESENT = 'DD_GO_VENDOR_PRESENT';
    case DD_GO_WORKSPACE_MODULE_MISSING = 'DD_GO_WORKSPACE_MODULE_MISSING';
    case DD_RUST_EDITION_MISSING = 'DD_RUST_EDITION_MISSING';
    case DD_RUST_GIT_DEPENDENCY = 'DD_RUST_GIT_DEPENDENCY';
    case DD_RUST_LOCK_MISSING = 'DD_RUST_LOCK_MISSING';
    case DD_RUST_NOT_PROJECT = 'DD_RUST_NOT_PROJECT';
    case DD_RUST_PATH_DEPENDENCY = 'DD_RUST_PATH_DEPENDENCY';
    case DD_RUST_READY = 'DD_RUST_READY';
    case DD_RUST_RELEASE_PROFILE_DEBUG = 'DD_RUST_RELEASE_PROFILE_DEBUG';
    case DD_RUST_TOOLCHAIN_DECLARED = 'DD_RUST_TOOLCHAIN_DECLARED';
    case DD_RUST_WORKSPACE_MEMBER_MISSING = 'DD_RUST_WORKSPACE_MEMBER_MISSING';
    case DD_JAVA_MIXED_BUILD_SYSTEMS = 'DD_JAVA_MIXED_BUILD_SYSTEMS';
    case DD_JAVA_NOT_PROJECT = 'DD_JAVA_NOT_PROJECT';
    case DD_JAVA_READY = 'DD_JAVA_READY';
    case DD_JAVA_RISKY_BUILD_SCRIPT = 'DD_JAVA_RISKY_BUILD_SCRIPT';
    case DD_JAVA_SPRING_PROD_DEBUG = 'DD_JAVA_SPRING_PROD_DEBUG';
    case DD_JAVA_VERSION_MISMATCH = 'DD_JAVA_VERSION_MISMATCH';
    case DD_JAVA_WRAPPER_MISSING = 'DD_JAVA_WRAPPER_MISSING';
    case DD_IAC_BACKEND_SECRET = 'DD_IAC_BACKEND_SECRET';
    case DD_IAC_LOCK_MISSING = 'DD_IAC_LOCK_MISSING';
    case DD_IAC_NOT_PROJECT = 'DD_IAC_NOT_PROJECT';
    case DD_IAC_READY = 'DD_IAC_READY';
    case DD_IAC_REMOTE_MODULE_UNPINNED = 'DD_IAC_REMOTE_MODULE_UNPINNED';
    case DD_IAC_SECRET_DEFAULT = 'DD_IAC_SECRET_DEFAULT';
    case DD_IAC_WILDCARD_PROVIDER_VERSION = 'DD_IAC_WILDCARD_PROVIDER_VERSION';
    case DD_KUBE_HELM_LOCK_MISSING = 'DD_KUBE_HELM_LOCK_MISSING';
    case DD_KUBE_HOST_PATH_MOUNT = 'DD_KUBE_HOST_PATH_MOUNT';
    case DD_KUBE_MUTABLE_IMAGE_TAG = 'DD_KUBE_MUTABLE_IMAGE_TAG';
    case DD_KUBE_NODEPORT_SERVICE = 'DD_KUBE_NODEPORT_SERVICE';
    case DD_KUBE_NOT_PROJECT = 'DD_KUBE_NOT_PROJECT';
    case DD_KUBE_PRIVILEGED_CONTAINER = 'DD_KUBE_PRIVILEGED_CONTAINER';
    case DD_KUBE_READY = 'DD_KUBE_READY';
    case DD_KUBE_VALUES_SECRET = 'DD_KUBE_VALUES_SECRET';
    case DD_DOTNET_LOCK_MISSING = 'DD_DOTNET_LOCK_MISSING';
    case DD_DOTNET_MIXED_SOLUTION_STATE = 'DD_DOTNET_MIXED_SOLUTION_STATE';
    case DD_DOTNET_NOT_PROJECT = 'DD_DOTNET_NOT_PROJECT';
    case DD_DOTNET_READY = 'DD_DOTNET_READY';
    case DD_DOTNET_RISKY_NUGET_SOURCE = 'DD_DOTNET_RISKY_NUGET_SOURCE';
    case DD_DOTNET_SDK_NOT_PINNED = 'DD_DOTNET_SDK_NOT_PINNED';
    case DD_DOTNET_TARGET_FRAMEWORK_MISMATCH = 'DD_DOTNET_TARGET_FRAMEWORK_MISMATCH';
    case DD_CPP_COMPILE_COMMANDS_MISSING = 'DD_CPP_COMPILE_COMMANDS_MISSING';
    case DD_CPP_GENERATOR_ASSUMPTION = 'DD_CPP_GENERATOR_ASSUMPTION';
    case DD_CPP_IN_SOURCE_BUILD = 'DD_CPP_IN_SOURCE_BUILD';
    case DD_CPP_MIXED_DEPENDENCY_MANAGERS = 'DD_CPP_MIXED_DEPENDENCY_MANAGERS';
    case DD_CPP_NOT_PROJECT = 'DD_CPP_NOT_PROJECT';
    case DD_CPP_READY = 'DD_CPP_READY';
    case DD_CPP_RISKY_COMPILER_FLAGS = 'DD_CPP_RISKY_COMPILER_FLAGS';
    case DD_CPP_SHELL_ASSUMPTION = 'DD_CPP_SHELL_ASSUMPTION';
    case DD_WEB_ASSET_REFERENCE_MISSING = 'DD_WEB_ASSET_REFERENCE_MISSING';
    case DD_WEB_BUILD_OUTPUT_MISSING = 'DD_WEB_BUILD_OUTPUT_MISSING';
    case DD_WEB_INSECURE_DEFAULT_CONFIG = 'DD_WEB_INSECURE_DEFAULT_CONFIG';
    case DD_WEB_NOT_PROJECT = 'DD_WEB_NOT_PROJECT';
    case DD_WEB_PORT_CONFIG_CONFLICT = 'DD_WEB_PORT_CONFIG_CONFLICT';
    case DD_WEB_PUBLIC_SECRET = 'DD_WEB_PUBLIC_SECRET';
    case DD_WEB_READY = 'DD_WEB_READY';
    case DD_SECURITY_DOCKER_PRIVILEGED = 'DD_SECURITY_DOCKER_PRIVILEGED';
    case DD_SECURITY_DOCKER_SOCKET_MOUNT = 'DD_SECURITY_DOCKER_SOCKET_MOUNT';
    case DD_SECURITY_ENV_NOT_IGNORED = 'DD_SECURITY_ENV_NOT_IGNORED';
    case DD_SECURITY_READY = 'DD_SECURITY_READY';
    case DD_SECURITY_RISKY_COMPOSER_SCRIPT = 'DD_SECURITY_RISKY_COMPOSER_SCRIPT';
    case DD_SECURITY_RISKY_PACKAGE_SCRIPT = 'DD_SECURITY_RISKY_PACKAGE_SCRIPT';
    case DD_SECURITY_SECRET_IN_EXAMPLE = 'DD_SECURITY_SECRET_IN_EXAMPLE';
    case DD_SECURITY_SECRET_PATTERN = 'DD_SECURITY_SECRET_PATTERN';
    case DD_DOCKER_BINARY_MISSING = 'DD_DOCKER_BINARY_MISSING';
    case DD_DOCKER_COMPOSE_CONFIG_INVALID = 'DD_DOCKER_COMPOSE_CONFIG_INVALID';
    case DD_DOCKER_COMPOSE_FILE_MISSING = 'DD_DOCKER_COMPOSE_FILE_MISSING';
    case DD_DOCKER_COMPOSE_INVALID = 'DD_DOCKER_COMPOSE_INVALID';
    case DD_DOCKER_CONTAINER_UNHEALTHY = 'DD_DOCKER_CONTAINER_UNHEALTHY';
    case DD_DOCKER_DAEMON_UNAVAILABLE = 'DD_DOCKER_DAEMON_UNAVAILABLE';
    case DD_DOCKER_ENV_REFERENCE_MISSING = 'DD_DOCKER_ENV_REFERENCE_MISSING';
    case DD_DOCKER_HOST_PORT_CONFLICT = 'DD_DOCKER_HOST_PORT_CONFLICT';
    case DD_DOCKER_NO_COMPOSE_PROJECT = 'DD_DOCKER_NO_COMPOSE_PROJECT';
    case DD_DOCKER_READY = 'DD_DOCKER_READY';
    case DD_ENV_DUPLICATE_KEY = 'DD_ENV_DUPLICATE_KEY';
    case DD_ENV_EMPTY_VALUE = 'DD_ENV_EMPTY_VALUE';
    case DD_ENV_EXAMPLE_MISSING = 'DD_ENV_EXAMPLE_MISSING';
    case DD_ENV_FILE_MISSING = 'DD_ENV_FILE_MISSING';
    case DD_ENV_FORBIDDEN_WHEN_PRESENT = 'DD_ENV_FORBIDDEN_WHEN_PRESENT';
    case DD_ENV_INVALID_ALLOWED_VALUE = 'DD_ENV_INVALID_ALLOWED_VALUE';
    case DD_ENV_INVALID_CONFIG = 'DD_ENV_INVALID_CONFIG';
    case DD_ENV_INVALID_KEY_NAME = 'DD_ENV_INVALID_KEY_NAME';
    case DD_ENV_INVALID_TYPE = 'DD_ENV_INVALID_TYPE';
    case DD_ENV_MISSING_IN_ENV = 'DD_ENV_MISSING_IN_ENV';
    case DD_ENV_MISSING_IN_EXAMPLE = 'DD_ENV_MISSING_IN_EXAMPLE';
    case DD_ENV_PROD_DEBUG = 'DD_ENV_PROD_DEBUG';
    case DD_ENV_READY = 'DD_ENV_READY';
    case DD_ENV_REQUIRED_MISSING = 'DD_ENV_REQUIRED_MISSING';
    case DD_ENV_REQUIRED_WHEN_MISSING = 'DD_ENV_REQUIRED_WHEN_MISSING';
    case DD_ENV_SECRET_IN_EXAMPLE = 'DD_ENV_SECRET_IN_EXAMPLE';
    case DD_GIT_AHEAD_BEHIND = 'DD_GIT_AHEAD_BEHIND';
    case DD_GIT_BINARY_MISSING = 'DD_GIT_BINARY_MISSING';
    case DD_GIT_CONFLICTS = 'DD_GIT_CONFLICTS';
    case DD_GIT_DETACHED_HEAD = 'DD_GIT_DETACHED_HEAD';
    case DD_GIT_DIRTY_WORKTREE = 'DD_GIT_DIRTY_WORKTREE';
    case DD_GIT_ENV_NOT_IGNORED = 'DD_GIT_ENV_NOT_IGNORED';
    case DD_GIT_LARGE_UNTRACKED_FILE = 'DD_GIT_LARGE_UNTRACKED_FILE';
    case DD_GIT_NOT_REPOSITORY = 'DD_GIT_NOT_REPOSITORY';
    case DD_GIT_NO_UPSTREAM = 'DD_GIT_NO_UPSTREAM';
    case DD_GIT_READY = 'DD_GIT_READY';
    case DD_GIT_TRACKED_SENSITIVE_FILE = 'DD_GIT_TRACKED_SENSITIVE_FILE';
    case DD_GIT_UNTRACKED_SENSITIVE_FILE = 'DD_GIT_UNTRACKED_SENSITIVE_FILE';
    case DD_PORTS_READY = 'DD_PORTS_READY';
    case DD_PORT_INVALID_PORT = 'DD_PORT_INVALID_PORT';
    case DD_PORT_IN_USE = 'DD_PORT_IN_USE';
    case DD_PORT_MULTIPLE_LISTENERS = 'DD_PORT_MULTIPLE_LISTENERS';
    case DD_PORT_PRIVILEGED = 'DD_PORT_PRIVILEGED';
    case DD_PORT_PROVIDER_UNAVAILABLE = 'DD_PORT_PROVIDER_UNAVAILABLE';
    case DD_PRESET_DETECTED = 'DD_PRESET_DETECTED';
    case DD_PRESET_NONE_DETECTED = 'DD_PRESET_NONE_DETECTED';
    case DD_QUEUE_CONNECTION_MISSING = 'DD_QUEUE_CONNECTION_MISSING';
    case DD_QUEUE_CONNECTION_UNKNOWN = 'DD_QUEUE_CONNECTION_UNKNOWN';
    case DD_QUEUE_DATABASE_REQUIRES_DB = 'DD_QUEUE_DATABASE_REQUIRES_DB';
    case DD_QUEUE_READY = 'DD_QUEUE_READY';
    case DD_QUEUE_REQUIRED_KEY_MISSING = 'DD_QUEUE_REQUIRED_KEY_MISSING';
    case DD_QUEUE_SYNC_IN_PRODUCTION = 'DD_QUEUE_SYNC_IN_PRODUCTION';

    public function hint(): ?string
    {
        return match ($this) {
            self::DD_CI_UNKNOWN_MODULE => 'Use one of the documented CI module names.',
            self::DD_CI_UNKNOWN_PROFILE => 'Use local, ci, strict-ci, or security.',
            self::DD_HEALTH_UNKNOWN_MODULE => 'Use one of the documented health module names or remove it from --modules.',
            self::DD_CI_BASELINE_MISSING => 'Create the baseline file with --write-baseline or correct the provided path.',
            self::DD_CI_BASELINE_INVALID => 'Regenerate the baseline file with --write-baseline.',
            self::DD_CI_BASELINE_EXISTS => 'Review the existing baseline before replacing it with --force.',
            self::DD_CI_BASELINE_REPORT => 'Use --write-baseline with --force after review to refresh resolved fingerprints.',
            self::DD_CACHE_DIRECTORY_LARGE => 'Review whether the cache can be pruned by the framework or package manager.',
            self::DD_CACHE_DIRECTORY_NOT_WRITABLE => 'Adjust ownership or permissions so the current user can write this runtime cache directory.',
            self::DD_CACHE_LARAVEL_ARTIFACT => 'Rebuild Laravel cache artifacts after changing configuration, routes, events, or packages.',
            self::DD_ENV_DUPLICATE_KEY => 'Keep a single declaration for this key so its effective value is unambiguous.',
            self::DD_ENV_EMPTY_VALUE => 'Set a meaningful value or explicitly ignore the key in devdoctor.yml.',
            self::DD_ENV_EXAMPLE_MISSING => 'Create the example file and document every required environment key.',
            self::DD_ENV_FILE_MISSING => 'Create the environment file from the project template before running the application.',
            self::DD_ENV_FORBIDDEN_WHEN_PRESENT => 'Remove or change this value when the configured condition is active.',
            self::DD_ENV_INVALID_ALLOWED_VALUE => 'Choose one of the values allowed by devdoctor.yml.',
            self::DD_ENV_INVALID_CONFIG => 'Fix the YAML structure and rerun DevDoctor.',
            self::DD_ENV_INVALID_KEY_NAME => 'Rename the key to use letters, numbers, and underscores only.',
            self::DD_ENV_INVALID_TYPE => 'Change the value to match the type declared in devdoctor.yml.',
            self::DD_ENV_MISSING_IN_ENV => 'Add the key to the environment file or ignore it explicitly when it is optional.',
            self::DD_ENV_MISSING_IN_EXAMPLE => 'Add the key to the example file without copying a real secret value.',
            self::DD_ENV_PROD_DEBUG => 'Disable debug mode before using production environment settings.',
            self::DD_ENV_REQUIRED_MISSING, self::DD_ENV_REQUIRED_WHEN_MISSING => 'Add the required key to the environment file.',
            self::DD_ENV_SECRET_IN_EXAMPLE => 'Replace the value with a safe placeholder and rotate the exposed credential if it was real.',
            self::DD_PORT_INVALID_PORT => 'Use a numeric TCP port between 1 and 65535.',
            self::DD_PORT_MULTIPLE_LISTENERS => 'Inspect all listeners and stop only the process that should not own the port.',
            self::DD_PORT_PROVIDER_UNAVAILABLE => 'Install a supported port inspection tool for this operating system.',
            self::DD_PORT_IN_USE => 'Confirm the process can be stopped before freeing the port.',
            self::DD_QUEUE_CONNECTION_MISSING => 'Set QUEUE_CONNECTION when the application relies on background jobs.',
            self::DD_QUEUE_CONNECTION_UNKNOWN => 'Use a supported queue connection name or document the custom driver intentionally.',
            self::DD_QUEUE_DATABASE_REQUIRES_DB => 'Configure database diagnostics first because database queues depend on DB settings.',
            self::DD_QUEUE_REQUIRED_KEY_MISSING => 'Add the required queue environment key or document an intentional runtime default.',
            self::DD_QUEUE_SYNC_IN_PRODUCTION => 'Use a real asynchronous queue driver before relying on production background jobs.',
            self::DD_COMPOSER_BINARY_MISSING => 'Install Composer or add it to PATH before running Composer diagnostics.',
            self::DD_COMPOSER_EXTENSION_MISSING => 'Install and enable the required PHP extension.',
            self::DD_COMPOSER_JSON_INVALID => 'Fix composer.json syntax before running Composer commands.',
            self::DD_COMPOSER_LOCK_MISSING, self::DD_COMPOSER_LOCK_OUTDATED => 'Review dependency changes and regenerate composer.lock intentionally.',
            self::DD_COMPOSER_PACKAGE_ABANDONED => 'Plan migration to a maintained replacement package.',
            self::DD_COMPOSER_PHP_VERSION_MISMATCH => 'Use a PHP version that satisfies composer.json or update the declared constraint intentionally.',
            self::DD_COMPOSER_SCRIPT_RISKY => 'Review the script and replace shell execution with a safer, auditable command where possible.',
            self::DD_COMPOSER_VALIDATE_FAILED => 'Run Composer validation for the full error details.',
            self::DD_COMPOSER_VENDOR_MISSING => 'Install dependencies after reviewing composer.lock.',
            self::DD_DB_CONNECT_FAILED => 'Verify credentials, host, port, and local network reachability before starting the application.',
            self::DD_DB_CONNECTION_MISSING => 'Set DB_CONNECTION to the database driver your project expects.',
            self::DD_DB_CONNECTION_UNKNOWN => 'Use a supported database connection name or document the custom driver intentionally.',
            self::DD_DB_DRIVER_MISSING => 'Install and enable the matching PDO driver for the active PHP runtime.',
            self::DD_DB_PORT_INVALID => 'Use a numeric TCP port between 1 and 65535.',
            self::DD_DB_REQUIRED_KEY_MISSING => 'Add the required database environment key or configure an intentional default.',
            self::DD_DB_SQLITE_FILE_MISSING => 'Create the SQLite database file intentionally before relying on it.',
            self::DD_HTTP_INSECURE_PRODUCTION_URL => 'Use an HTTPS URL for production-facing endpoints.',
            self::DD_HTTP_LOCALHOST_PRODUCTION_URL => 'Replace localhost with the canonical production or staging host.',
            self::DD_HTTP_URL_INVALID => 'Use a fully qualified http or https URL.',
            self::DD_HTTP_URL_MISSING => 'Set APP_URL or provide an explicit --url when HTTP URL diagnostics matter.',
            self::DD_PHP_BINARY_MISSING => 'Install PHP or add it to PATH before running PHP diagnostics.',
            self::DD_PHP_COMPOSER_JSON_INVALID => 'Fix composer.json syntax before relying on PHP platform diagnostics.',
            self::DD_PHP_EXTENSION_MISSING => 'Install and enable the required PHP extension for the active CLI runtime.',
            self::DD_PHP_INI_MISSING => 'Confirm the CLI runtime is intentionally running without a php.ini file.',
            self::DD_PHP_MEMORY_LIMIT_LOW => 'Increase CLI memory_limit or run DevDoctor with a lower intentional threshold.',
            self::DD_PHP_VERSION_MISMATCH => 'Use a PHP runtime that satisfies composer.json or update the declared constraint intentionally.',
            self::DD_PHP_XDEBUG_ENABLED_IN_CI => 'Disable Xdebug in CI, for example by setting XDEBUG_MODE=off.',
            self::DD_NODE_BINARY_MISSING => 'Install Node.js or add it to PATH before running Node diagnostics.',
            self::DD_NODE_LOCK_MISSING => 'Generate and commit the intended package manager lockfile.',
            self::DD_NODE_LOCK_OUTDATED => 'Regenerate the lockfile with the package manager selected by the project.',
            self::DD_NODE_MODULES_MISSING => 'Install dependencies with the package manager selected by the project lockfile.',
            self::DD_NODE_MULTIPLE_LOCKFILES => 'Keep only the lockfile for the package manager the project actually uses.',
            self::DD_NODE_PACKAGE_JSON_INVALID => 'Fix package.json syntax before running package manager commands.',
            self::DD_NODE_PACKAGE_MANAGER_MISMATCH => 'Align packageManager with the committed lockfile.',
            self::DD_NODE_SCRIPT_RISKY => 'Review the script and replace remote shell execution with a safer, auditable command.',
            self::DD_NODE_VERSION_FILE_CONFLICT => 'Choose one Node.js version policy and align package.json, .nvmrc, and .node-version.',
            self::DD_NODE_VERSION_MISMATCH => 'Use a Node.js runtime that satisfies the project requirement.',
            self::DD_LARAVEL_APP_KEY_MISSING => 'Generate and set APP_KEY before running the application.',
            self::DD_LARAVEL_APP_URL_DEFAULT => 'Set APP_URL to the canonical local, staging, or production URL for this project.',
            self::DD_LARAVEL_CONFIG_CACHED => 'Rebuild Laravel config cache after changing environment or config files.',
            self::DD_LARAVEL_DIRECTORY_MISSING => 'Create the expected Laravel runtime directory.',
            self::DD_LARAVEL_DIRECTORY_NOT_WRITABLE => 'Adjust ownership or permissions so the current user can write Laravel runtime files.',
            self::DD_LARAVEL_ENV_MISSING => 'Create .env from .env.example and fill required Laravel values.',
            self::DD_LARAVEL_PROD_DEBUG => 'Disable APP_DEBUG before using production environment settings.',
            self::DD_MCP_CONFIG_INVALID => 'Fix the JSON syntax before relying on MCP server configuration.',
            self::DD_MCP_COMMAND_RISKY => 'Review the command and replace shell evaluation or remote script execution with a pinned executable.',
            self::DD_MCP_ENV_REFERENCE_MISSING => 'Declare the referenced environment key in .env or .env.example, or document the external secret source.',
            self::DD_MCP_ENV_SECRET_INLINE => 'Move the secret value to an environment variable and rotate it if the value was real.',
            self::DD_MCP_REMOTE_URL_INSECURE => 'Use HTTPS for remote MCP servers unless the URL is an intentional localhost endpoint.',
            self::DD_MCP_REMOTE_URL_MISSING => 'Add the remote MCP server URL or switch the server to stdio with a command.',
            self::DD_MCP_SERVER_INVALID => 'Use a named MCP server object with a supported transport, command, or URL.',
            self::DD_MCP_SERVERS_MISSING => 'Define MCP servers under mcpServers or servers.',
            self::DD_MCP_STDIO_COMMAND_MISSING => 'Add the command used to start the stdio MCP server.',
            self::DD_MCP_TRANSPORT_UNKNOWN => 'Use stdio, sse, or http as the MCP server transport.',
            self::DD_SYMFONY_ENV_MISSING => 'Create .env from .env.example or document the environment source used by Symfony.',
            self::DD_SYMFONY_PROD_DEBUG => 'Disable APP_DEBUG before using prod environment settings.',
            self::DD_SYMFONY_RECIPE_DRIFT => 'Review Symfony Flex recipes and ensure expected config files are committed.',
            self::DD_SYMFONY_RISKY_COMPOSER_SCRIPT => 'Review Composer scripts before running install, update, or Symfony recipe tasks.',
            self::DD_SYMFONY_RUNTIME_DIR_MISSING => 'Create the expected Symfony runtime directory or confirm it is generated during deployment.',
            self::DD_SYMFONY_SECRET_MISSING => 'Set APP_SECRET to a non-default value before running the application.',
            self::DD_FRONTEND_BUILD_SCRIPT_MISSING => 'Add a build script or document why this frontend project is served without a build step.',
            self::DD_FLUTTER_DEPENDENCY_SOURCE => 'Review local path and Git dependencies before publishing or running CI.',
            self::DD_FLUTTER_LOCK_MISSING => 'Generate and commit pubspec.lock for Flutter applications after reviewing dependency changes.',
            self::DD_FLUTTER_PLATFORM_MARKERS_MISSING => 'Confirm whether this is a package-only project or regenerate the intended Flutter platform folders.',
            self::DD_FLUTTER_SDK_CONSTRAINT_MISSING => 'Declare the supported Dart SDK range in pubspec.yaml.',
            self::DD_MOBILE_ANDROID_DEBUGGABLE => 'Disable debuggable mode outside local debug variants.',
            self::DD_MOBILE_ANDROID_WRAPPER_MISSING => 'Commit the Gradle wrapper so Android builds use a predictable tool version.',
            self::DD_MOBILE_IOS_DEBUG_ENTITLEMENT => 'Remove get-task-allow from release entitlements.',
            self::DD_MOBILE_IOS_POD_LOCK_MISSING => 'Run CocoaPods dependency resolution intentionally and commit Podfile.lock.',
            self::DD_MONOREPO_LOCK_MISSING => 'Generate and commit the lockfile for the workspace package manager.',
            self::DD_MONOREPO_MIXED_TOOLS => 'Document the intended orchestration split or remove stale monorepo tool config.',
            self::DD_MONOREPO_RISKY_ROOT_SCRIPT => 'Review root lifecycle scripts before installing workspace dependencies.',
            self::DD_PYTHON_LOCK_MISSING => 'Commit the lockfile generated by the selected Python dependency manager.',
            self::DD_PYTHON_MIXED_MANAGERS => 'Choose one Python dependency manager policy and remove stale manifest or lock files.',
            self::DD_PYTHON_SUSPICIOUS_SOURCE => 'Review custom package indexes, URL dependencies, and VCS dependencies before installing.',
            self::DD_PYTHON_VERSION_CONFLICT => 'Align Python version constraints across project files.',
            self::DD_PYTHON_VENV_MISSING => 'Create a local virtual environment or document the Conda environment used by the project.',
            self::DD_RUBY_DATABASE_SECRET => 'Move database credentials to environment variables or encrypted credentials.',
            self::DD_RUBY_LOCK_MISSING => 'Generate and commit Gemfile.lock for applications.',
            self::DD_RUBY_RAILS_MASTER_KEY_MISSING => 'Provide RAILS_MASTER_KEY through the environment or document credential handling.',
            self::DD_RUBY_RISKY_GEM_SOURCE => 'Review HTTP, Git, and path gem sources before installing dependencies.',
            self::DD_RUBY_VERSION_CONFLICT => 'Align Ruby version declarations across Gemfile and version files.',
            self::DD_GO_MODULE_PATH_INVALID => 'Use the canonical Go module path declared by the repository or package namespace.',
            self::DD_GO_REPLACE_DIRECTIVE => 'Review local replace directives before committing them because they may only work on one machine.',
            self::DD_GO_SUM_MISSING => 'Regenerate go.sum intentionally after reviewing go.mod dependency changes.',
            self::DD_GO_WORKSPACE_MODULE_MISSING => 'Fix the go.work use path or add the missing module go.mod file.',
            self::DD_RUST_EDITION_MISSING => 'Declare the intended Rust edition in Cargo.toml.',
            self::DD_RUST_GIT_DEPENDENCY => 'Review Git dependencies and pin revisions intentionally before relying on them.',
            self::DD_RUST_LOCK_MISSING => 'Commit Cargo.lock for Rust applications and binaries.',
            self::DD_RUST_PATH_DEPENDENCY => 'Review local path dependencies because they may not work outside this checkout.',
            self::DD_RUST_RELEASE_PROFILE_DEBUG => 'Review release profile settings before publishing optimized builds.',
            self::DD_RUST_WORKSPACE_MEMBER_MISSING => 'Fix the workspace member path or add the missing Cargo.toml.',
            self::DD_JAVA_MIXED_BUILD_SYSTEMS => 'Choose the intended JVM build system and remove stale build files.',
            self::DD_JAVA_RISKY_BUILD_SCRIPT => 'Review shell execution in build files before running builds or dependency tasks.',
            self::DD_JAVA_SPRING_PROD_DEBUG => 'Disable debug logging for production Spring profiles.',
            self::DD_JAVA_VERSION_MISMATCH => 'Align Java version declarations across Maven, Gradle, and toolchain configuration.',
            self::DD_JAVA_WRAPPER_MISSING => 'Commit the Maven or Gradle wrapper so builds use a predictable tool version.',
            self::DD_IAC_BACKEND_SECRET => 'Move backend credentials out of Terraform files and into environment or secret manager configuration.',
            self::DD_IAC_LOCK_MISSING => 'Run the appropriate init flow intentionally and commit the provider lockfile.',
            self::DD_IAC_REMOTE_MODULE_UNPINNED => 'Pin remote modules to an immutable ref or version.',
            self::DD_IAC_SECRET_DEFAULT => 'Remove secret-like defaults from variable declarations.',
            self::DD_IAC_WILDCARD_PROVIDER_VERSION => 'Pin provider versions to a bounded constraint.',
            self::DD_KUBE_HELM_LOCK_MISSING => 'Regenerate Chart.lock intentionally after reviewing chart dependency changes.',
            self::DD_KUBE_HOST_PATH_MOUNT => 'Avoid hostPath mounts unless the workload explicitly needs host filesystem access.',
            self::DD_KUBE_MUTABLE_IMAGE_TAG => 'Pin images to immutable tags or digests before deployment.',
            self::DD_KUBE_NODEPORT_SERVICE => 'Confirm NodePort exposure is intentional for the target cluster.',
            self::DD_KUBE_PRIVILEGED_CONTAINER => 'Remove privileged mode or document why host-level container privileges are required.',
            self::DD_KUBE_VALUES_SECRET => 'Move real secret values into Kubernetes Secrets, sealed secrets, or external secret tooling.',
            self::DD_DOTNET_LOCK_MISSING => 'Generate and commit packages.lock.json intentionally when restore lock mode is enabled.',
            self::DD_DOTNET_MIXED_SOLUTION_STATE => 'Keep one canonical solution file or document why multiple solutions are maintained.',
            self::DD_DOTNET_RISKY_NUGET_SOURCE => 'Use HTTPS package sources or document the trusted internal feed explicitly.',
            self::DD_DOTNET_SDK_NOT_PINNED => 'Add global.json when the repository expects a specific .NET SDK version.',
            self::DD_DOTNET_TARGET_FRAMEWORK_MISMATCH => 'Review target frameworks and align them unless the split is intentional.',
            self::DD_CPP_COMPILE_COMMANDS_MISSING => 'Enable CMAKE_EXPORT_COMPILE_COMMANDS when editor tooling or static analysis needs it.',
            self::DD_CPP_GENERATOR_ASSUMPTION => 'Avoid hard-coding CMake generators in project files; choose generators in presets or CI.',
            self::DD_CPP_IN_SOURCE_BUILD => 'Move generated CMake build artifacts out of the source tree.',
            self::DD_CPP_MIXED_DEPENDENCY_MANAGERS => 'Choose one C/C++ dependency manager policy or document the split explicitly.',
            self::DD_CPP_RISKY_COMPILER_FLAGS => 'Review compiler flags that can hide diagnostics or weaken build hardening.',
            self::DD_CPP_SHELL_ASSUMPTION => 'Replace Unix-only shell assumptions or guard them for cross-platform builds.',
            self::DD_WEB_ASSET_REFERENCE_MISSING => 'Fix the asset path or add the referenced file before serving the page.',
            self::DD_WEB_BUILD_OUTPUT_MISSING => 'Run the documented build step or point DevDoctor at the generated output directory.',
            self::DD_WEB_INSECURE_DEFAULT_CONFIG => 'Review whether this web server setting is safe for the intended environment.',
            self::DD_WEB_PORT_CONFIG_CONFLICT => 'Align the port used by environment config and frontend scripts.',
            self::DD_WEB_PUBLIC_SECRET => 'Move secrets out of public web files and rotate exposed credentials if they were real.',
            self::DD_SECURITY_DOCKER_PRIVILEGED => 'Avoid privileged containers unless the service explicitly requires host-level access.',
            self::DD_SECURITY_DOCKER_SOCKET_MOUNT => 'Avoid mounting the Docker socket into containers unless this is an intentional trusted control plane.',
            self::DD_SECURITY_ENV_NOT_IGNORED => 'Add .env patterns to .gitignore to reduce accidental secret commits.',
            self::DD_SECURITY_RISKY_COMPOSER_SCRIPT => 'Review the Composer script and replace remote shell execution with a safer install step.',
            self::DD_SECURITY_RISKY_PACKAGE_SCRIPT => 'Review the package script and replace remote shell execution with a safer install step.',
            self::DD_SECURITY_SECRET_IN_EXAMPLE => 'Replace the value with a placeholder and rotate the credential if it was real.',
            self::DD_SECURITY_SECRET_PATTERN => 'Move hard-coded secrets into a secret manager or local environment file and rotate exposed values.',
            self::DD_GIT_BINARY_MISSING => 'Install Git or add it to PATH before running repository diagnostics.',
            self::DD_GIT_CONFLICTS => 'Resolve all merge conflicts before continuing.',
            self::DD_GIT_DETACHED_HEAD => 'Create or switch to a branch before making long-lived changes.',
            self::DD_GIT_DIRTY_WORKTREE => 'Review, commit, stash, or discard the intended changes before requiring a clean worktree.',
            self::DD_GIT_ENV_NOT_IGNORED => 'Add the environment file pattern to .gitignore.',
            self::DD_GIT_LARGE_UNTRACKED_FILE => 'Review whether the file belongs in Git or should be ignored or stored elsewhere.',
            self::DD_GIT_NO_UPSTREAM => 'Configure an upstream branch before relying on ahead/behind diagnostics.',
            self::DD_GIT_TRACKED_SENSITIVE_FILE => 'Remove the file from version control and rotate any exposed credentials.',
            self::DD_GIT_UNTRACKED_SENSITIVE_FILE => 'Ignore the file or confirm it cannot be committed accidentally.',
            self::DD_DOCKER_BINARY_MISSING => 'Install Docker or add it to PATH before running Compose diagnostics.',
            self::DD_DOCKER_COMPOSE_CONFIG_INVALID, self::DD_DOCKER_COMPOSE_INVALID => 'Fix the Compose configuration before starting containers.',
            self::DD_DOCKER_COMPOSE_FILE_MISSING => 'Check the --compose-file path or add a supported Compose file.',
            self::DD_DOCKER_CONTAINER_UNHEALTHY => 'Inspect container logs and health-check output before restarting services.',
            self::DD_DOCKER_DAEMON_UNAVAILABLE => 'Start the Docker daemon and verify the current user can access it.',
            self::DD_DOCKER_ENV_REFERENCE_MISSING => 'Define the referenced environment variable or provide an intentional Compose default.',
            self::DD_DOCKER_HOST_PORT_CONFLICT => 'Change the host port mapping or stop the process currently using that port.',
            default => null,
        };
    }
}
