<?php

declare(strict_types=1);

namespace DevDoctor\Core\Config;

use DevDoctor\Core\PathResolver;
use DevDoctor\Modules\Env\EnvEntry;
use DevDoctor\Modules\Env\EnvParser;
use DevDoctor\Modules\Presets\PresetDetector;
use Symfony\Component\Yaml\Yaml;

final readonly class ConfigWizard
{
    public function __construct(
        private EnvParser $envParser = new EnvParser,
        private PresetDetector $presetDetector = new PresetDetector,
    ) {}

    public function generate(string $path): string
    {
        $paths = PathResolver::fromBasePath($path);
        $envFile = $this->firstExisting($paths, ['.env', '.env.local']) ?? '.env';
        $exampleFile = $this->firstExisting($paths, ['.env.example', '.env.dist', '.env.sample']) ?? '.env.example';
        $source = is_file($paths->absolute($exampleFile)) ? $exampleFile : $envFile;
        $entries = is_file($paths->absolute($source))
            ? $this->envParser->parseFile($paths->absolute($source), $source)->entries
            : [];

        $rules = [];

        foreach ($entries as $entry) {
            $rule = $this->inferRule($entry, $source === $exampleFile);

            if ($rule !== []) {
                $rules[$entry->key] = $rule;
            }
        }

        $config = [
            'modules' => [
                'env' => [
                    'files' => [
                        'env' => $envFile,
                        'example' => $exampleFile,
                    ],
                ],
            ],
        ];

        if ($rules !== []) {
            $config['modules']['env']['rules'] = $rules;
        }

        $presets = array_map(
            static fn ($match): string => $match->preset->value,
            $this->presetDetector->detect($path),
        );

        $header = '# Generated by DevDoctor';

        if ($presets !== []) {
            $header .= ' for detected presets: '.implode(', ', $presets);
        }

        return $header.PHP_EOL.Yaml::dump($config, 6, 2, Yaml::DUMP_MULTI_LINE_LITERAL_BLOCK).PHP_EOL;
    }

    /**
     * @return array<string, mixed>
     */
    private function inferRule(EnvEntry $entry, bool $required): array
    {
        $rule = $required ? ['required' => true] : [];
        $type = $this->inferType($entry->key, $entry->value);

        if ($type !== null) {
            $rule['type'] = $type;
        }

        return $rule;
    }

    private function inferType(string $key, string $value): ?string
    {
        if (preg_match('/^(true|false)$/i', $value) === 1) {
            return 'bool';
        }

        if (preg_match('/^-?\d+$/', $value) === 1) {
            return 'int';
        }

        if (str_ends_with($key, '_URL') && filter_var($value, FILTER_VALIDATE_URL) !== false) {
            return 'url';
        }

        return null;
    }

    /**
     * @param  list<string>  $files
     */
    private function firstExisting(PathResolver $paths, array $files): ?string
    {
        foreach ($files as $file) {
            if (is_file($paths->absolute($file))) {
                return $file;
            }
        }

        return null;
    }
}
